### PR TITLE
create nav with home and bootstrap

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tsimonq2** [comment]
Hmm, I was hoping to get some actual content there, so functionality is priority over aesthetics. Thank you for doing this, as we will need it in the future, but I don't think we are ready to transition yet. Check the TODO.md for the current item that we are working on. Although, it does look really really nice, and it seems to function good. I am having Alex make us a logo for the navigation bar. This overall so far looks like exactly the direction that we should go with this. Again, I just want to make it functional first. THEN we can go ahead and implement this. So keep updating your fork, and when we get to that point, I will be happy to merge it. :)

**Comment by ghost** [comment]
Have you given this a test? It does work for the most part. But what I need is content. I'm actually not a very active member since my class happens around meetings. Let me know exactly what to improve on. Thanks.

**Comment by tsimonq2** [comment]
I have given it a test. It works great, it looks awesome, but we just need _content_. So yes, I think we should implement this, but we need content.

After we get content, I plan on merging. But for now, what you can do is track our changes and keep a fork of it which uses Bootstrap. Then when I am ready, I will merge it. You could do that, or when I let you know, sync the changes and do the Bootstrap all at once. Your choice. We should collaborate in IRC to know when this happens. Here is more details on that: https://wiki.ubuntu.com/WisconsinTeam#Communication

**Comment by ghost** [comment]
Thank you for clarifying. I will keep my fork updated and watch this repos.

**Pull request closed without merging**
